version: "3"
services:
  application:
    container_name: application
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis_database
    environment:
      REDIS_HOST: redis_database
      REDIS_PORT: 6379
  redis_database:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

